### PR TITLE
Problem: Cannot access xrap_msg metadata and parameters from bindings

### PR DESCRIPTION
**Pull request by sappo**
Solution: Add the according methods to the api file

### CODE REVIEW

**Comment by c-rack** [comment]
Would merge this, but don't have write access to do so.
Seems zwebrap is not in the list of core repos:
https://github.com/orgs/zeromq/teams/core/repositories

**Comment by c-rack** [comment]
But I don't know if it is by purpose or by mistake :-)

**Comment by sappo** [comment]
@c-rack by mistake ;) Should work now. Thanks!

**Comment by c-rack** [comment]
:+1:

**Pull request merged**
