### PR TITLE
out of sync with zproject

### PR DESCRIPTION
**Pull request by sappo**

### CODE REVIEW

**Comment by bluca** [comment]
Looks like the repository of one of the dependency is not right:

```
+git clone --depth 1 http://ftp.gnu.org/gnu/libmicrohttpd/ libmicrohttpd
Cloning into 'libmicrohttpd'...
fatal: repository 'http://ftp.gnu.org/gnu/libmicrohttpd/' not found
```

**Comment by sappo** [comment]
It's been like this for a while. libmicrohttpd devs are still using subversion. I hadn't had the time to investigate how to solve this issue in zproject.

**Comment by bluca** [comment]
Agh, SVN! It would be nice if a dependency could be built from a tarball in zproject :-)

**Comment by sappo** [comment]
Yes, that would have been my idea as well.

**Pull request merged**
